# OvertimeOverview — common developer tasks.
#
# Project is generated by Tuist (the *.xcodeproj / *.xcworkspace are generated and must be
# regenerated after adding/removing source files).
#
# Quick start:
#   make generate     generate the Xcode project/workspace and open it in Xcode
#   make update       resolve SPM deps, then regenerate (run after editing Package.swift)
#   make compile      build the app
#
# Run `make help` for the full list.
APP_PATH := OvertimeOverview

.DEFAULT_GOAL := help

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

# ──────────────────────────────── Project generation ────────────────────────────────

.PHONY: generate
generate: ## Generate the Xcode project/workspace and open it in Xcode
	tuist generate --path $(APP_PATH)

.PHONY: update
update: ## Resolve SPM deps, then regenerate (run after editing Package.swift)
	tuist install --path $(APP_PATH)
	tuist generate --path $(APP_PATH)

# ─────────────────────────────────── Building ───────────────────────────────────────

.PHONY: compile
compile: ## Build the app
	tuist build --path $(APP_PATH)

.PHONY: test
test: ## Run the unit tests (known tail noise: ~10 min of simulator diagnostics after the run)
	tuist test --path $(APP_PATH)

# ──────────────────────────────────── Cleaning ──────────────────────────────────────

.PHONY: clean
clean: ## Remove Tuist-generated project files and build artifacts
	tuist clean
	rm -rf $(APP_PATH)/Derived Derived build .build